db:
  dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
  dataSource:
    url: jdbc:postgresql://localhost:5432/books
    username: postgres
    password: admin
  hikari:
    minimumIdle: 5
    maximumPoolSize: 10
    connectionTimeout: 30000
    idleTimeout: 600000
    maxLifetime: 1800000
